---
- hosts: all  # Define target hosts
  remote_user: ubuntu  # Define the user to connect to the remote hosts
  become: yes  # Use sudo privileges

  vars:
    docker_image: "containerguru1/wed-proj-1"
    docker_tag: "latest"
    container_name: "wed-proj-1"

  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      docker_login:
        username: "containerguru1"
        password: "Madmithra!27"

    - name: Stop the running container (if any)
      docker_container:
        name: "{{ container_name }}"
        state: stopped
      ignore_errors: true

    - name: Remove the stopped container (if any)
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: true

    - name: Remove the existing Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        state: absent
      ignore_errors: true

    - name: Pull the Docker image from Docker Hub
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull

    - name: Start the Docker container with the new image
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
